# Generated by Django 4.2.4 on 2023-08-09 03:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu", "0005_alter_category_category_name_alter_category_slug_and_more"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cart",
            new_name="CartItem",
        ),
    ]
