# Generated by Django 4.2.4 on 2023-08-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
