# Generated by Django 4.2.4 on 2023-08-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor", "0001_initial"),
        ("menu", "0004_alter_category_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("vendor", "category_name", "slug")},
        ),
    ]
