# Generated by Django 4.2.4 on 2023-08-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "Chờ Xử Lý"),
                    ("Accepted", "Đã Chấp Nhận"),
                    ("Completed", "Đã Hoàn Thành"),
                    ("Cancelled", "Đã Hủy"),
                ],
                default="New",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
