# Generated by Django 4.2.4 on 2023-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_status_alter_order_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedfood",
            name="price",
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
    ]
